### ISSUE TITLE
możliwe definiowanie czasu załączenia przekaźnika

### ISSUE THREAD

**Issue by Espablo** [Espablo/GUI-Generic#10]

**Comment by gmx168** [comment]
W niektórych projektach domowych bardzo przydatne --> np. zamiast przenosić do scen albo dodawania funkcjonalności zewnętrznych na monostabilnych NE555, funkcjonalność da możliwość zdefiniowania w przypadku wyjścia przekaźnikowego trybu monostabilnego w odróżnieniu od obecnego bistabilnego.

Taka mikro-funkcjonalność istnieje przy zdefiniowaniu wyjścia jako funkcji otwarcia furtki/bramy - wtedy jest wybór 0,5 - 1- 2sekundy.

**Comment by Espablo** [comment]
Czas załączenia przekaźnika pobierany jest z supla cloud
