### ISSUE TITLE
literówki

### ISSUE THREAD

**Issue by gmx168** [Espablo/GUI-Generic#15]
In case of Polish language in the application there is a specific error. It is only valid in polish language.

W przypadku zdefiniowania czujnika otwarcia - bez zdefiniowania własnej nazwy - publikowany jest napis "czujnik otwacia". Widziałem "otwacia" nie tylko w tekscie opisującym czujnik furtki ale także bramy.

**Comment by Espablo** [comment]
To jest błąd w supla cloud
